# dbt/dbt_project.yml
config-version: 2

name: 'demo-dbt'
version: '1.0'
profile: 'demo-dbt_profile'

model-paths: ["models"]

models:
  demo-dbt:          # ← impératif : ce nom doit matcher le champ `name:` plus haut
    raw:             # ← on cible le dossier models/raw/
      +schema: RAW_LAYER
      +materialized: table
