name: demo_dbt
profile: demo_dbt_profile

model-paths: ["models"]

models:
  demo_dbt:
    raw:
      +materialized: table
    bronze:
      +materialized: table
    silver:
      +materialized: table

# ---------- déclenchement automatique des pipes ----------
on-run-start:
  - "{{ create_raw_pipes() }}"
