# dbt/dbt_project.yml
config-version: 2

name: 'demo_dbt'
version: '1.0'
profile: 'demo_dbt_profile'

models:
  # on ne met plus demo_dbt: ici
  raw:
    +schema: RAW_LAYER
    +materialized: table
