config-version: 2
name: 'demo_dbt'         # ⬅️ si ton dossier s’appelle demo-dbt, pense à matcher ici
version: '1.0'
profile: 'demo_dbt_profile'

model-paths: ["models"]

models:
  demo_dbt:
    raw:
      +schema: RAW_LAYER
      +materialized: table
