name: demo_dbt
version: "1.0"
config-version: 2          

model-paths: ["models"]

models:
  demo_dbt:
    +schema_suffix: ""      # désactive tout suffixe automatique

    # Modèles RAW → DAS tables dans RAW_LAYER
    raw:
      +schema: RAW_LAYER
      +materialized: table

   
