name: demo_dbt
version: "1.0"
profile: demo_dbt_profile

model-paths: ["models"]

models:
  dbt:
    +schema_suffix: ""        # empêche RAW_RAW_LAYER

    raw:
      +schema: RAW_LAYER
      +materialized: table
      +schema_suffix: ""

    bronze:
      +schema: BRONZE_LAYER
      +materialized: table
      +schema_suffix: ""

    silver:
      +schema: SILVER_LAYER
      +materialized: table
      +schema_suffix: ""

    gold:
      +schema: GOLD_LAYER
      +materialized: table
      +schema_suffix: ""
