name: demo_dbt
profile: demo_dbt_profile

model-paths: ["models"]

models:
  demo_dbt:
    raw:
      +materialized: table
      +full_refresh: false
    bronze:
      +materialized: table
    silver:
      +materialized: table
    operations:
      raw_to_bronze_proc:
       vars:
          pipe_table_name: 'PRC_CAMPAIGN_RAW'
          unique_key: ['HouseKey','CampaignCode']  # ou juste 'HouseKey' si simple
vars:
  SF_DATABASE: TEST_POC_VISEO_DB
  SF_SCHEMA: RAW_LAYER

  pipe_configs:
  - name: pipe_prc_campaign
    stage: EXTERNAL_AZURE_STAGE
    table: PRC_CAMPAIGN_RAW
    unique_key: ['APUKCODE']
    pattern: ".*PRC_CAMPAIGN_.*\\.csv"
    columns:
      - HouseKey
      - CampaignCode
      - CampaignName
      - CampaignDescription
      - HistoricalSellInFirstMonth
      - HistoricalSellInLastMonth
      - CampaignDate
      - SYS_SOURCE_DATE
    file_format:
      field_delimiter: ';'
      skip_header: 1
      field_optionally_enclosed_by: '"'

  - name: pipe_prc_benchmark
    stage: EXTERNAL_AZURE_STAGE
    table: PRC_BENCHMARK_RAW
    unique_key: ['HouseKey','CampaignCode']
    pattern: ".*PRC_BENCHMARK_.*\\.csv"
    columns:
      - APUKCODE
      - ANABENCH2CODE
      - ANABENCH2
      - SKUGroup
      - SYS_SOURCE_DATE
    file_format:
      field_delimiter: ';'
      skip_header: 1
      field_optionally_enclosed_by: '"'

