# dbt_project.yml  (à la racine du repo)
config-version: 2

name: 'demo_dbt'
version: '1.0'
profile: 'demo_dbt_profile'

model-paths: ["models"]

models:
  demo_dbt:
    raw:
      +schema: RAW_LAYER       # override complet du schema
      +materialized: table
