name: demo_dbt
profile: demo_dbt_profile

model-paths: ["models"]

models:
  demo_dbt:
    raw:
      +materialized: table
    bronze:
      +materialized: table
    silver:
      +materialized: table

vars:
  pipe_configs:
    - name: pipe_prc_benchmark
      stage: EXTERNAL_AZURE_STAGE
      table: RAW_LAYER.PRC_BENCHMARK_RAW
      pattern: ".*PRC_BENCHMARK_.*\\.csv"

    - name: pipe_prc_campaign
      stage: EXTERNAL_AZURE_STAGE
      table: RAW_LAYER.PRC_CAMPAIGN_RAW
      pattern: ".*PRC_CAMPAIGN_.*\\.csv"


