name: demo_dbt
version: "1.0"
profile: demo_dbt_profile

model-paths: ["models"]

models:
  demo_dbt:
    +schema_suffix: ""
    raw:
      +schema: RAW_LAYER
      +materialized: table
      +schema_suffix: ""
    
