demo_dbt_profile:          
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user:    "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"   
      role:     "{{ env_var('SF_ROLE') }}"
      database: "TEST_POC_VISEO_DB"
      warehouse: "{{ env_var('SF_WAREHOUSE') }}"
      schema:   dev
      threads:  4
